#pragma config(Motor,  port1,           armMotor1,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          armMotor2,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  while(1 == 1)
  {
    //Driving Motor Control
    motor[leftMotor] = vexRT[Ch3];
    motor[rightMotor] = vexRT[Ch2];

    //Arm Control
    if(vexRT[Btn6U] == 1)
    {
      motor[armMotor1] = 100;
      motor[armMotor2] = 100;
    }
    else if(vexRT[Btn6D] == 1)
    {
      motor[armMotor1] = -40;
      motor[armMotor2] = -40;
    }
    else
    {
      motor[armMotor1] = 0;
      motor[armMotor2] = 0;
    }
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
